DROP TABLE IF EXISTS ProductCategory;
DROP TABLE IF EXISTS Supplier;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Location;
DROP TABLE IF EXISTS "Order";
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Stock;
DROP TABLE IF EXISTS OrderDetail;

CREATE TABLE ProductCategory
(
    CATEGORYID INT PRIMARY KEY,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255)
);
CREATE TABLE Supplier
(
    SUPPLIERID INT PRIMARY KEY,
    NAME VARCHAR(255)
);
CREATE TABLE Customer
(
    CUSTOMERID INT PRIMARY KEY,
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    USERNAME VARCHAR(255)
);
CREATE TABLE Location
(
    LOCATIONID INT PRIMARY KEY,
    NAME VARCHAR(255),
    COUNTRY VARCHAR(255),
    CITY VARCHAR(255),
    REGION VARCHAR(255),
    ADDRESS VARCHAR(255)
);
CREATE TABLE "Order"
(
    ORDERID INT PRIMARY KEY,
    LOCATIONID INT,
    CUSTOMERID INT,
    CITY VARCHAR(255),
    REGION VARCHAR(255),
    ADDRESS VARCHAR(255),
    COUNTRY VARCHAR(255),
    CONSTRAINT Order_ShippedFrom FOREIGN KEY (LOCATIONID) REFERENCES Location (LOCATIONID),
    CONSTRAINT Order_Customer FOREIGN KEY (CUSTOMERID) REFERENCES Customer (CUSTOMERID)
);
CREATE TABLE Product
(
    PRODUCTID INT PRIMARY KEY,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    PRICE DECIMAL,
    WEIGHT DOUBLE,
    CATEGORYID INT,
    SUPPLIERID INT,
    CONSTRAINT Product_Category FOREIGN KEY (CATEGORYID) REFERENCES ProductCategory (CATEGORYID),
    CONSTRAINT Product_Supplier FOREIGN KEY (SUPPLIERID) REFERENCES Supplier (SUPPLIERID)
);
CREATE TABLE Stock
(
    PRODUCTID INT,
    LOCATIONID INT,
    QUANTITY INT,
    CONSTRAINT Stock_pk PRIMARY KEY (PRODUCTID, LOCATIONID),
    CONSTRAINT Stock_Product FOREIGN KEY (PRODUCTID) REFERENCES Product (PRODUCTID),
    CONSTRAINT Stock_Location FOREIGN KEY (LOCATIONID) REFERENCES Location (LOCATIONID)
);
CREATE TABLE OrderDetail
(
    ORDERID INT,
    PRODUCTID INT,
    QUANTITY INT,
    CONSTRAINT OrderDetail_pk PRIMARY KEY (ORDERID, PRODUCTID),
    CONSTRAINT OrderDetail_Order FOREIGN KEY (ORDERID) REFERENCES "Order" (ORDERID),
    CONSTRAINT OrderDetail_Product FOREIGN KEY (PRODUCTID) REFERENCES Product (PRODUCTID)
);
