CREATE TABLE authority 
  ( 
     authority_id   INTEGER GENERATED BY DEFAULT AS IDENTITY, 
     authority_name VARCHAR(255) NOT NULL, 
     PRIMARY KEY (authority_id) 
  ); 

CREATE TABLE customer 
  ( 
     first_name   VARCHAR(255), 
     last_name    VARCHAR(255), 
     user_user_id INTEGER NOT NULL, 
     PRIMARY KEY (user_user_id) 
  ); 

CREATE TABLE location 
  ( 
     location_id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
     city        VARCHAR(255), 
     country     VARCHAR(255), 
     address     VARCHAR(255), 
     region      VARCHAR(255), 
     name        VARCHAR(255), 
     PRIMARY KEY (location_id) 
  ); 

CREATE TABLE order_detail 
  ( 
     orderid   INTEGER NOT NULL, 
     productid INTEGER NOT NULL, 
     quantity  INTEGER NOT NULL, 
     PRIMARY KEY (orderid, productid) 
  ); 

CREATE TABLE order_table 
  ( 
     order_id              INTEGER GENERATED BY DEFAULT AS IDENTITY, 
     city                  VARCHAR(255), 
     country               VARCHAR(255), 
     address               VARCHAR(255), 
     region                VARCHAR(255), 
     customer_user_user_id INTEGER, 
     location_location_id  INTEGER, 
     PRIMARY KEY (order_id) 
  ); 

CREATE TABLE product 
  ( 
     product_id  INTEGER GENERATED BY DEFAULT AS IDENTITY, 
     description VARCHAR(255), 
     name        VARCHAR(255), 
     price       DECIMAL(19, 2), 
     weight      DOUBLE NOT NULL, 
     categoryid  INTEGER, 
     supplierid  INTEGER, 
     PRIMARY KEY (product_id) 
  ); 

CREATE TABLE productcategory 
  ( 
     category_id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
     description VARCHAR(255), 
     name        VARCHAR(255), 
     PRIMARY KEY (category_id) 
  ); 

CREATE TABLE stock 
  ( 
     locationid INTEGER NOT NULL, 
     productid  INTEGER NOT NULL, 
     quantity   INTEGER NOT NULL, 
     PRIMARY KEY (locationid, productid) 
  ); 

CREATE TABLE supplier 
  ( 
     supplier_id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
     name        VARCHAR(255), 
     PRIMARY KEY (supplier_id) 
  ); 

CREATE TABLE user_table 
  ( 
     user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY, 
     PASSWORD VARCHAR(255), 
     username VARCHAR(255) NOT NULL, 
     PRIMARY KEY (user_id) 
  ); 

CREATE TABLE users_authority 
  ( 
     authority_id INTEGER, 
     user_id      INTEGER NOT NULL, 
     PRIMARY KEY (user_id) 
  ); 

ALTER TABLE authority 
  ADD CONSTRAINT authority_name_unique UNIQUE (authority_name);

ALTER TABLE location 
  ADD CONSTRAINT location_name_unique UNIQUE (name);

ALTER TABLE product 
  ADD CONSTRAINT product_name_unique UNIQUE (name);

ALTER TABLE productcategory 
  ADD CONSTRAINT productcat_name_unique UNIQUE (name);

ALTER TABLE supplier 
  ADD CONSTRAINT supplier_name_unique UNIQUE (name);

ALTER TABLE user_table 
  ADD CONSTRAINT user_name_unique UNIQUE (username);

ALTER TABLE customer 
  ADD CONSTRAINT customer_user_fk FOREIGN KEY (user_user_id)
  REFERENCES user_table; 

ALTER TABLE order_detail 
  ADD CONSTRAINT orderdetail_order_fk FOREIGN KEY (orderid) REFERENCES
  order_table; 

ALTER TABLE order_detail 
  ADD CONSTRAINT orderdetail_product_fk FOREIGN KEY (productid) REFERENCES
  product; 

ALTER TABLE order_table 
  ADD CONSTRAINT order_customer_fk FOREIGN KEY (customer_user_user_id)
  REFERENCES customer; 

ALTER TABLE order_table 
  ADD CONSTRAINT order_location_fk FOREIGN KEY (location_location_id)
  REFERENCES location; 

ALTER TABLE product 
  ADD CONSTRAINT product_category_fk FOREIGN KEY (categoryid) REFERENCES
  productcategory; 

ALTER TABLE product 
  ADD CONSTRAINT product_supplier_fk FOREIGN KEY (supplierid) REFERENCES
  supplier; 

ALTER TABLE stock 
  ADD CONSTRAINT stock_location_fk FOREIGN KEY (locationid) REFERENCES
  location; 

ALTER TABLE stock 
  ADD CONSTRAINT stock_product_fk FOREIGN KEY (productid) REFERENCES
  product; 

ALTER TABLE users_authority 
  ADD CONSTRAINT userauthority_authority_fk FOREIGN KEY (authority_id)
  REFERENCES authority; 

ALTER TABLE users_authority 
  ADD CONSTRAINT userauthortity_user_fk FOREIGN KEY (user_id) REFERENCES
  user_table; 