DROP TABLE revenue IF EXISTS;

CREATE TABLE revenue
(
  revenue_id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
  DATE                 DATE,
  total_revenue        DECIMAL(19, 2),
  location_id INTEGER,
  PRIMARY KEY (revenue_id)
);

ALTER TABLE revenue
  ADD CONSTRAINT revenue_location_fk FOREIGN KEY (location_id)
REFERENCES location;

ALTER TABLE order_table
  ADD column revenued BOOLEAN DEFAULT(false);